name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

      - uses: viswiz-io/github-action@refactor/pnpm
        with:
          api-key: ${{ secrets.VISWIZ_API_KEY }}
          images-directory: ./output/
          project-id: 25p4pYTp6CjE9oANcgJpaU
