name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn

      - run: yarn test

      - uses: viswiz-io/github-action@v1.0.2
        with:
          api-key: ${{ secrets.VISWIZ_API_KEY }}
          images-directory: ./output/
          project-id: 25p4pYTp6CjE9oANcgJpaU
