name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: git
        run: |
          echo "::set-output name=branch_name::${GITHUB_REF##ref/heads/}"
          echo "::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)"
          echo "::set-output name=commit_sha::$(git log --format=%H -n 1 HEAD)"

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn
      - run: yarn test
        env:
          GITHUB_BRANCH_NAME: ${{ steps.git.outputs.branch_name }}
          GITHUB_COMMIT_MESSAGE: ${{ steps.git.outputs.commit_message }}
          GITHUB_COMMIT_SHA: ${{ steps.git.outputs.commit_sha }}
          VISWIZ_API_KEY: ${{ secrets.VISWIZ_API_KEY }}
          VISWIZ_PROJECT_ID: 25p4pYTp6CjE9oANcgJpaU
